@url = http://localhost:3001/api
@json = Content-Type: application/json
### 查询所有学生
GET {{url}}/getAllUsers
{{json}}

### 注册
POST {{url}}/register
{{json}}

{
  "id": "stu2",
  "password": "123456"
}

### 登录
POST {{url}}/login
{{json}}

{
  "id": "admin3",
  "password": "123456"
}

### 使用token admin3
GET {{url}}/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjQ2OGVlYmUwZGU0MmZhMDc0ODU5NCIsImlhdCI6MTY3NzE3NjcyN30.gOlJCwrA2zCr5EitEq1XXA71iHDlEzgvNO5gTZ9ynWw

### 重置密码
POST  {{url}}/resetPassword
{{json}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjQ2OGVlYmUwZGU0MmZhMDc0ODU5NCIsImlhdCI6MTY3NzE3NjcyN30.gOlJCwrA2zCr5EitEq1XXA71iHDlEzgvNO5gTZ9ynWw

{
  "id": "2019001"
}

### 全部学生信息
GET {{url}}/studentsInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjQ2OGVlYmUwZGU0MmZhMDc0ODU5NCIsImlhdCI6MTY3NzE3NjcyN30.gOlJCwrA2zCr5EitEq1XXA71iHDlEzgvNO5gTZ9ynWw